# Generated by Django 3.1.2 on 2021-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
