# Generated by Django 3.1.2 on 2021-04-16 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatify', '0002_auto_20210415_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='CrimeAlert',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='CrimeDetection',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='CrimeSensitivity',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='MotionAlert',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='MotionDetection',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='MotionSensitivity',
        ),
        migrations.AddField(
            model_name='user',
            name='CrimeAlert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='CrimeDetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='CrimeSensitivity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='MotionAlert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='MotionDetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='MotionSensitivity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
