# Generated by Django 3.1.2 on 2021-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatify', '0003_auto_20210417_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='Confidence',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='Duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='File',
            field=models.CharField(max_length=300),
        ),
    ]
