# Generated by Django 3.1.2 on 2021-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatify', '0004_auto_20210422_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='Confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='Duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
